name: Deploy

on:
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "18.x"
        cache: 'npm'
    - run: npm ci
    - run: npm run codegen && npm run build
    - run: npm run graph:auth
      env:
        GRAPH_AUTH_TOKEN: ${{ secrets.GRAPH_AUTH_TOKEN }}
    - run: npm run deploy:hosted